spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_project_v1
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true
